### ISSUE TITLE
Consider adding $variables

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#11]
Command | Description
--- | ---
[variable]=[value] | Set variable equal to value
[command] $[variable] | Use variable's value by adding $ before the name

## Examples

```bash
x=12345
echo $x
```

```bash
timestamp=`date +%Y-%m-%d`
echo $timestamp;
```

```bash
hello=hello;
world=world;
echo $hello $world
```

**Comment by 0nn0** [comment]
Not considered basics in my opinion, therefore leaving it out for now. Thanks for the suggestions though!
