### ISSUE TITLE
Consider adding 'chown [options] [user] [file/folder]'

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#12]
Consider adding [chown](https://en.wikipedia.org/wiki/Chown)

Command | Description
--- | ----
chown [options] [user] [file/folder] | Change the owner of a file
chown -f -R [user] [folder] | Change the owner of a folder and files recursively

## Examples

```bash
chown -f apache filename.txt
```

```bash
sudo chown -f -R user:group /dir
```

**Comment by 0nn0** [comment]
Not considered basics therefore for now not included. Thanks for the suggestion though!
