### ISSUE TITLE
Consider adding tar, gzip, bzip2, zip

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#14]
Command | Description
--- | ---
tar -zcvf [.tgz-file] [files] | Zip files with gzip compression
tar -jcvf [.tbz2-file] [files] | Zip files with bzip2 compression
gzip -f -9 [file] | Zip file
tar -zxvf [.tgz-file] | Decompress file
tar -jxvf [.tbz2-file] | Decompress file

## Examples

**Compress** 

```bash
timestamp=`date +%Y-%m-%d`
tar -zcvf archive.$timestamp.tar.gz myFolder
```

```bash
tar -zcvf data.tgz *.doc
tar -zcvf pics.tar.gz *.jpg *.png
tar -jcvf data.tbz2 *.doc
ls -l
```

```bash 
gzip mydata.doc
gzip *.jpg
ls -l
```

```bash 
bzip2 mydata.doc
bzip2 *.jpg
ls -l
```

```bash 
zip mydata.zip mydata.doc
zip data.zip *.doc
ls -l
```

**Decompress** 

```bash
tar -zxvf data.tgz 
tar -zxvf pics.tar.gz *.jpg
tar -jxvf data.tbz2
```

```bash
gzip -d mydata.doc.gz
gunzip mydata.doc.gz
```

```bash
bzip2 -d mydata.doc.bz2
gunzip mydata.doc.bz2
```

```bash
unzip file.zip
unzip data.zip resume.doc
```

**Links** 

[Bash Zip CheatSheet](http://www.cyberciti.biz/howto/question/general/compress-file-unix-linux-cheat-sheet.php)

**Comment by 0nn0** [comment]
Not included for now, in order to keep things simple. Will reconsider if there are more requests. Thanks!
