### ISSUE TITLE
Consider adding grep

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#15]
Consider adding [grep](http://www.shellhacks.com/en/Using-BASH-Grep-OR-Grep-AND-Grep-NOT-Operators)

Command | Description
--- | ----
grep [search_pattern] [file] | Search for all lines that contain the pattern
grep -v [search_pattern] [file] | Search for all lines that do not contain the pattern
[string] \| grep [search_pattern] | Search string for matches

## Examples

**Contents of filename.txt**
```text
a/b/c
a/b/c.zip
```

**Search File Contents**
```bash
# find all lines that contain "a/b/c"
grep "a/b/c" filename.txt

# find all lines that contain "a/b/c" or print if none are found.
grep "a/b/c" filename.txt || printf "\nNo Matches Found.\n"

# find all lines that contain "a/b/c" and do not include ".zip"
grep "a/b/c" filename.txt | grep -v ".zip"
```

**Search Command History**

```bash
# find all lines in bash history that contain the search_pattern
history | grep search_pattern
```

**Comment by 0nn0** [comment]
Added basic grep commands, thanks!
