### ISSUE TITLE
Consider adding pbcopy, pbpaste

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#16]
Consider adding [pbcopy, pbpaste](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pbcopy.1.html)

Command | Description
--- | ----
pbcopy < [file] | Copies file contents to clipboard
pbpaste | Paste clipboard contents

**Comment by 0nn0** [comment]
Added, thanks!
