### ISSUE TITLE
Consider adding apropos

### ISSUE THREAD

**Issue by PatrickEGorman** [0nn0/terminal-mac-cheatsheet#17]
Command | Description
------------ | -------------
Apropos [search-pattern] | Searches for command with keywords in description

I think this command is essential for finding new terminal commands.  It really opens the user up to new options.  It's especially useful with either -h or man [command] to look around for something that can fulfill a specific task

**Comment by legolas9** [comment]
Thank you Patrick, I will make a note on it.

**Comment by 0nn0** [comment]
Added, thanks!
