### ISSUE TITLE
cheatsheet disappeared?

### ISSUE THREAD

**Issue by i0sdev** [0nn0/terminal-mac-cheatsheet#3]
really?

**Comment by 0nn0** [comment]
It's still there: https://github.com/0nn0/terminal-mac-cheatsheet

**Comment by i0sdev** [comment]
What I could find is only README. If going to the wiki link in README, it comes to a blank page.

**Comment by 0nn0** [comment]
You're right! Not sure how it got deleted, haven't touched this repo in a while. Can anyone modify the wiki page?

I've restored the WIKI. Thanks a lot for pointing that out!

**Comment by 0nn0** [comment]
I've restricted editing of the WIKI to collaborators only for now, to avoid that the WIKI get erased again.

**Comment by i0sdev** [comment]
thanks a lot! This is a really handy tool!
