### ISSUE TITLE
What does ⌘Cmd + L do?

### ISSUE THREAD

**Issue by rosetree** [0nn0/terminal-mac-cheatsheet#35]
I accidentally typed ⌘Cmd + L in my Mac-Terminal and it seemed to delete the output of the previous command. I'm not sure how this shortcut is defined or where I can look it up. Does anybody have an idea?

**Comment by DwayneJ23** [comment]
It clears the terminal screen.

Here's a list of useful shortcuts:

https://github.com/0nn0/terminal-mac-cheatsheet

**Comment by ogirginc** [comment]
Are you sure it wasn't <kbd>⌘Cmd</kbd>+<kbd>K</kbd>, as both keys are next to each other? As far as I know, there isn't a default shortcut for <kbd>⌘Cmd</kbd>+<kbd>L</kbd>.

**Comment by 0nn0** [comment]
Not aware that the shortcut <kbd>⌘Cmd</kbd>+<kbd>L</kbd> exists either.

**Comment by rosetree** [comment]
Please excuse my late reply. I double checked, that I used <kbd>⌘Cmd</kbd>+<kbd>L</kbd> and not <kbd>⌘Cmd</kbd>+<kbd>K</kbd>. I also looked up my custom keyboard commands in the profile settings. But <kbd>⌘Cmd</kbd>+<kbd>L</kbd> was not defined there (similar to <kbd>⌘Cmd</kbd>+<kbd>K</kbd> or others). So I would argue that this is a default behavior. I’m using Terminal Version 2.7.2 (388.1).

**Comment by 0nn0** [comment]
@rosetree: Just tried it in the Terminal and you are right! It seems that <kbd>⌘Cmd</kbd>+<kbd>L</kbd> removes the previously executed command. Can you confirm that?

**Comment by rosetree** [comment]
Thanks for your reply. This is also how I would describe this command. It removes the output and the prompt. But not the history entry.

**Comment by cduguet** [comment]
Did you guys figure out how to bring it back???

**Comment by ugurcemozturk** [comment]
Well, so give it a try to ⌘Cmd+Alt+L. Removes the whole universe.

**Comment by HoseynHeydari** [comment]
⌘Cmd+Alt+L , ⌘Cmd+L , ⌘Cmd+K
all seems the same for me.
@ugurcemozturk What do you mean by "whole universe" please?

**Comment by snez** [comment]
Confirmed ⌘Cmd+Alt+L removes the whole universe :(

**Comment by dbajpai29** [comment]
clear==⌘Cmd+Alt+L

**Comment by ShivamPokhriyal** [comment]
Is there an alternative of Cmd+L for linux?

**Comment by alecglen** [comment]
FYI, under "Edit" ⌘Cmd+L is labelled as "Clear to Previous Mark"

**Comment by TonyBarganski** [comment]
Very disconcerting, especially when in a bunch of tmux panes. 
Fortunately, pressing <ENTER> in each panes/window brings everything back - phew! :)
