### ISSUE TITLE
Add how to run commands sequentially or parallel

### ISSUE THREAD

**Issue by alexilyaev** [0nn0/terminal-mac-cheatsheet#37]
Hi, this repo is great, serving as a good reference.

Can you add flow control tips?

- `command && command`
- `command || command`
- Same things just with one `&` (what's the difference?)
- command & (I think it put the result in a background process?)

Thanks

**Comment by 0nn0** [comment]
@alexilyaev Thanks for your message! You can find these flow control tips in "CHAINING COMMANDS"
