### ISSUE TITLE
Ctrl + Q doesn't work to clear everything on current line

### ISSUE THREAD

**Issue by manniamc** [0nn0/terminal-mac-cheatsheet#47]

**Comment by 0nn0** [comment]
@manniamc Are you using the default terminal on Mac? Can you explain when it does not work?

**Comment by JonathanShor** [comment]
Doesn't work for me either. Doesn't work at all, ever, as far as I can tell. Never knew about this hot-key, and I guess now I never will. :)

Using one of the default profiles `Basic` on macOS 10.13.1. Terminal reports Version 2.8 (400).

**Comment by 15814** [comment]
It seems becomes Ctrl+w in my mac (System Version: macOS 10.13.2 (17C205))

**Comment by twhitt14** [comment]
Doesn't work for me either - this command should be removed

**Comment by JonathanShor** [comment]
Hmm, actually, ctrl+Q seems to do SOMETHING, just not deleting the line.

It seems to toggle a mode where then next keypress is printed directly to the line instead of being interpreted. For example, if you hit ctrl+Q and then ctrl+W, it prints `^W` to the line (instead of deleting the previous word, as ctrl+W normally does).

**Comment by HoseynHeydari** [comment]
@JonathanShor 
I try do what you say above but it doesn't work.

Using one of the default profiles Basic on macOS 10.13.3. Terminal reports Version 2.8 (400).

**Comment by JonathanShor** [comment]
@HoseynHeydari That's bizarre. I'm able to reproduce it now an macOS 10.13.4, Terminal Version 2.8.2 (404).

**Comment by HoseynHeydari** [comment]
@JonathanShor I try all keyboard and find that ctrl+V for me does what ctrl+Q does for you.

**Comment by JonathanShor** [comment]
@HoseynHeydari Interestingly, ctrl+V also works for me, along with ctrl+Q.

**Comment by CodySchrank** [comment]
Neither ctrl+Q or ctrl+V works for me.   The only combination that will clear a line for me is ctrl+C.  macOS 10.13.4, Terminal 2.8.2

**Comment by JonathanShor** [comment]
@CodySchrank 
Just for clarity, we found ctrl+V to have a different function, not that it clears the line for us.

**Comment by ZeroFlatline** [comment]
To clear everything in the current line. I usually use ctrl+U.
Hope that help.

**Comment by CodySchrank** [comment]
@JonathanShor Ahh now I see what you were saying.  For the mode changer ctrl+Q does not for me, but ctrl+V does.

@ZeroFlatline Ctrl+U works, but the cursor has to be at the end of the line.  Its actual function is to clear everything in front of the cursor.

So far ctrl+C is the only shortcut that clears the line for me with the cursor at any position.

**Comment by JonathanShor** [comment]
Yeah, with ctrl+U and ctrl+K (clear everything after the cursor), you can get the same result ultimately.

@CodySchrank  Ctrl+C is an option, but just have to keep in mind that you're sending a reset to the terminal, which is much stronger than just clearing the text on the current line in some circumstances.
And so weird I have this random ctrl+Q!

**Comment by CodySchrank** [comment]
@JonathanShor There are certainly some pitfalls with using ctrl + C but I don't think I've ever accidentally killed something when trying to clear a line.  I made a PR removing ctrl + Q and added a note that ctrl + C can be used to clear a line.
