### ISSUE TITLE
PDF version of cheatsheet.

### ISSUE THREAD

**Issue by Dmytro-Kovbasa** [0nn0/terminal-mac-cheatsheet#48]
What about PDF version? I'd like to print it and put in front of my eyes.

**Comment by 0nn0** [comment]
@Dmytro-Kovbasa If you're on Mac, simply:
1. Hit cmd+p (File > Print) 
2. Change destination to "Save as PDF" 
3. Hit Save

Option: Make a selection of the part you'd like to print, hit cmd+p and within "More settings" check "Selection only".
