### ISSUE TITLE
Running an app from Flash Drive

### ISSUE THREAD

**Issue by XVGMonk** [0nn0/terminal-mac-cheatsheet#49]
Hi,

I don't know if I'm the right place but here is what I'm trying to do.

Goal: Open an app from any mac using a flash drive.

I'm trying to run an app (QT Wallet app) from my flashdrive, this app requires to have information from it's library folder. 

The app itself does not give me the option to re route the library folder thats also on the flashdrive.

Is possible to use terminal? Or perhaps use alias in this case?

Thank you!

**Comment by 0nn0** [comment]
Hi @XVGMonk, unfortunately don't have any experience with running an app from a flash drive using the cli. Perhaps www.stackoverflow.com can help you further.
