### ISSUE TITLE
UPDATES?

### ISSUE THREAD

**Issue by snowparrot1** [0nn0/terminal-mac-cheatsheet#54]
Thank you for your work I appreciate been looking for a quick refresher on the key commands. And to all of those whose key commands were having issues. If a CMD'let is not working properly or to your specific requirements then altering the command individually is always an option and updating the profile with the custom cmdlets. Or you could begin to understand the light shinning behind the darkness and begin researching Darwin Series in MAC and why it was discontinued. Then maybe you can understand why things in our lives have stopped be so reliant on our personal control and we now have assistance wether we ask for it or not. ::Only after one opens their mind to the realm of possibilities;; then one can begin to open their mouth and say::: MOO!!!!!!!

**Comment by 00100120sm** [comment]
Good
