### ISSUE TITLE
Translate Wiki into Latin American Spanish

### ISSUE THREAD

**Issue by mixolidia** [0nn0/terminal-mac-cheatsheet#6]
I'd like to do a translation of this wiki into Latin American Spanish.
I've already started. Is this ok?

**Comment by 0nn0** [comment]
I'd say go for it @mixolidia ! At the moment I am considering to move all docs from the WIKI to individual readme files, since it will allow me to easily merge in other contributions.

**Comment by mixolidia** [comment]
Cool! Thanks! Will try and do both wiki and Read.me then.
