### ISSUE TITLE
Typo, Replace 'fi' with 'file'

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#8]
Seems like in the description you meant 'file' instead of 'fi'.

[https://github.com/0nn0/terminal-mac-cheatsheet/wiki/Terminal-Cheatsheet-for-Mac-(-basics-)](https://github.com/0nn0/terminal-mac-cheatsheet/wiki/Terminal-Cheatsheet-for-Mac-(-basics-))

Command | Description
--- | ---
<	| Tell command to read content from a fi

**Comment by 0nn0** [comment]
@jgraup Sharp eye! Thanks for the correction!
