### ISSUE TITLE
Consider adding 'chmod +x [file]'

### ISSUE THREAD

**Issue by jgraup** [0nn0/terminal-mac-cheatsheet#9]
I seem to use [chmod](https://en.wikipedia.org/wiki/Chmod) quite a bit.

Command | Description
--- | ----
chmod [options] mode[,mode] file1 [file2 ...] | Change the access permissions to file system objects
chmod +x  [file] | Allow file to be executed

## Example

Allow file to be executed
```bash
chmod +x file.sh
```

File Contents
```bash
#!/bin/bash
printf "chmod Rocks! \n\n";
```

Execute file from the command line
```bash
./file.sh
```

Output
```bash
chmod Rocks!


```

**Comment by 0nn0** [comment]
Not included for now, but will reconsider if more requests. Thanks for you many suggestions though!

**Comment by duncangh** [comment]
**more requests**
